"""add user foreign key to monitors

Revision ID: 33057099abdd
Revises: 489e2a8cd747
Create Date: 2026-10-09 20:32:38.344392

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33057099abdd"
down_revision: Union[str, Sequence[str], None] = "489e2a8cd747"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "monitors_user_id_fkey", "monitors", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("monitors_user_id_fkey", "monitors", type_="foreignkey")
    # ### end Alembic commands ###
